INSERT INTO UNIDADE_FEDERATIVA(CODIGOUF, NOME, SIGLA) VALUES(1, 'Santa Catarina', 'SC');
INSERT INTO UNIDADE_FEDERATIVA(CODIGOUF, NOME, SIGLA) VALUES(2, 'Rio Grande do sul', 'RS');


INSERT INTO municipio(CODIGO_MUNICIPIO, CODIGOIBGE, NOMEIBGE, CODIGO_REGIAO, PAIS, CODIGOUF) VALUES (1, 4307005, 'Erechim', '2', 'Brasil', 2);

INSERT INTO USUARIO(CODIGO_USUARIO, ADM, EMAIL, NOME, SENHA, CODIGO_MUNICIPIO) VALUES (1, true, 'teste@teste.com', 'Teste', '123', 1);